# -*- coding: utf-8 -*-
"""Le plan du livre. Une entrée = une double page."""

# (ordre, titre, question, resume, [idées])
PLAN = {
0: [
 (1,"Pourquoi ce livre","Pourquoi un livre de plus sur l'alimentation ?",
  "La documentation disponible prescrit ou reste illisible ; presque rien n'explique le mécanisme.",
  ["Deux familles de sources : les instructions, et la recherche illisible hors de sa discipline",
   "L'espace vide entre les deux : ce qui se passe à l'intérieur du corps",
   "Ce livre décrit, il ne prescrit pas — la décision appartient au lecteur"]),
 (2,"Comment lire ce livre","Comment lire ce livre ?",
  "Chaque double page se suffit à elle-même et répond à une question.",
  ["Lecture dans l'ordre ou par entrées séparées",
   "Une double page = une question = un mécanisme",
   "Les renvois nomment les notions empruntées aux autres pages"]),
 (3,"Promesse et limites","Que peut ce livre, et que ne peut-il pas ?",
  "Il explique des mécanismes ; il ne remplace ni un médecin ni un diagnostic.",
  ["Aucun chiffre présenté comme un objectif",
   "Aucune donnée sans sa source",
   "Les mécanismes sont décrits avec leurs limites et leurs débats ouverts",
   "Ce qui relève du médecin y reste"]),
 (4,"Sommaire visuel","De quoi ce livre parle-t-il, en une image ?",
  "Le plan du livre en une planche, des mécanismes jusqu'aux applications.",
  ["Les sept parties et leur enchaînement",
   "Ce que le lecteur sait faire au sortir de chacune"]),
],
1: [
 (1,"Le voyage d'une bouchée","Où va un aliment après la première bouchée ?",
  "Le trajet complet, de la mastication au tissu adipeux, en une planche.",
  ["Les étapes et leurs durées réelles","Où chaque macronutriment est absorbé",
   "Ce que le corps prélève, ce qu'il laisse passer"]),
 (2,"La bouche, première usine","Que se passe-t-il avant même d'avaler ?",
  "La mastication et la salive commencent la digestion et préviennent le cerveau.",
  ["L'amylase salivaire attaque l'amidon dès la bouche",
   "La mastication réduit la matrice et accélère l'absorption plus tard",
   "La phase céphalique : le corps se prépare avant que rien n'arrive"]),
 (3,"L'estomac, le réservoir acide","À quoi sert vraiment l'estomac ?",
  "Il stocke, acidifie, et règle le débit vers l'intestin — c'est ce débit qui compte.",
  ["La vidange gastrique et ce qui la ralentit",
   "Le volume perçu et les mécanorécepteurs de la paroi",
   "Pourquoi un même repas liquide et solide ne rassasie pas pareil"]),
 (4,"L'intestin grêle, l'aspirateur","Où les nutriments passent-ils dans le sang ?",
  "Six mètres de surface repliée où presque tout est absorbé.",
  ["Villosités et microvillosités : la surface réelle",
   "Ce qui est absorbé, et le peu qui ne l'est pas",
   "Le cas des amandes : l'énergie qui traverse sans être prise"]),
 (5,"Le microbiote, l'organe oublié","Que font les bactéries de l'intestin ?",
  "Elles digèrent ce que le corps ne sait pas digérer, et produisent des molécules actives.",
  ["Les fibres fermentées en acides gras à chaîne courte",
   "Ce que le microbiote extrait en plus des étiquettes",
   "Ce qui est établi et ce qui reste spéculatif"]),
 (6,"Foie et reins, les vrais organes d'épuration","Le corps a-t-il besoin d'être détoxifié ?",
  "Deux organes font ce travail en continu ; aucune cure ne s'y substitue.",
  ["Ce que le foie transforme réellement",
   "Ce que les reins filtrent et éliminent",
   "Pourquoi les cures détox n'ont pas de cible physiologique"]),
 (7,"Le glucose et l'insuline","Que devient le sucre une fois dans le sang ?",
  "L'insuline ouvre les portes des cellules et décide de l'ordre d'utilisation.",
  ["La glycémie monte, l'insuline répond, la glycémie redescend",
   "Le glycogène d'abord, le reste ensuite",
   "Ce que veut dire « pic » et ce que ça ne veut pas dire"]),
 (8,"Le stockage : la mise en réserve","Comment le corps met-il de l'énergie de côté ?",
  "Deux réserves de tailles très inégales : le glycogène et le tissu adipeux.",
  ["Le glycogène : petit, rapide, saturé vite",
   "Le tissu adipeux : quasi illimité",
   "Les trois routes qui mènent au gras"]),
 (9,"Le déstockage : quand la réserve s'ouvre","À quelle condition le corps puise-t-il dans ses réserves ?",
  "Le déstockage demande une baisse de l'insuline et un besoin non couvert.",
  ["Ce qui autorise la lipolyse","Pourquoi elle s'arrête dès qu'un apport arrive",
   "L'alternance quotidienne stockage / déstockage"]),
 (10,"Les hormones de la faim","Qu'est-ce qui déclenche la faim ?",
  "La ghréline appelle, la leptine informe des réserves, et les deux se dérèglent.",
  ["Ghréline : le signal qui monte avant les repas habituels",
   "Leptine : le niveau des réserves, et la résistance à son signal",
   "Pourquoi la faim suit les habitudes autant que les besoins"]),
 (11,"Faim ou envie","La faim et l'envie de manger sont-elles la même chose ?",
  "Deux circuits distincts : le besoin homéostatique et la récompense.",
  ["Le circuit du besoin et celui du plaisir",
   "Comment on peut avoir envie sans avoir faim",
   "Ce que la vue et l'odeur déclenchent à elles seules"]),
 (12,"La satiété : ce qui fait qu'on s'arrête","Qu'est-ce qui fait qu'on arrête de manger ?",
  "Trois signaux successifs : le volume, les hormones intestinales, puis les réserves.",
  ["Le volume gastrique, immédiat","Les hormones intestinales, en vingt minutes",
   "Pourquoi manger vite fait dépasser le point d'arrêt",
   "Densité énergétique : le déterminant le mieux étayé"]),
 (13,"Le rythme circadien","L'heure à laquelle on mange change-t-elle quelque chose ?",
  "La tolérance au glucose et la dépense varient au fil de la journée.",
  ["L'horloge interne et ses horloges périphériques",
   "Ce que la littérature établit et ce qu'elle discute encore"]),
 (14,"Récapitulatif de la partie","Que se passe-t-il, en résumé, quand on mange ?",
  "Le trajet complet et les points où une décision alimentaire agit.",
  ["Les six étapes en une planche","Les trois leviers réels sur ce trajet"]),
],
}

PLAN[2] = [
 (1,"Manger, c'est quoi","Qu'est-ce que le corps reçoit vraiment quand on mange ?",
  "Un repas apporte de la matière et, en même temps, un jeu de signaux.",
  ["La matière : ce que mesure l'étiquette","Les signaux : ce qui décide de l'usage",
   "Pourquoi deux repas identiques en calories ne se valent pas"]),
 (2,"Les trois macronutriments","Que sont les protéines, les glucides et les lipides ?",
  "Trois familles, trois rôles, trois destins différents dans le corps.",
  ["Ce que chacun construit, alimente ou met en réserve",
   "Les proportions dans une alimentation courante","Ce qu'aucun ne remplace"]),
 (3,"Protéines : les briques","À quoi servent les protéines ?",
  "Elles construisent et réparent ; le corps n'en fait pas de réserve.",
  ["Acides aminés essentiels et non essentiels","Pourquoi il n'existe pas de stock de protéines",
   "L'effet thermique le plus élevé des trois macros"]),
 (4,"Glucides : le carburant","À quoi servent les glucides ?",
  "Le carburant le plus rapide, et le seul dont le cerveau dépend directement.",
  ["Simples et complexes : une distinction qui vieillit mal",
   "Le glycogène, réserve courte","Ce qui se passe quand elle est pleine"]),
 (5,"Lipides : la réserve","À quoi servent les lipides ?",
  "Densité énergétique maximale, rôle structurel, et une mauvaise réputation à nuancer.",
  ["9 kcal par gramme : pourquoi","Saturés, insaturés, trans : ce qui les sépare",
   "Le rôle dans les membranes et les hormones"]),
 (6,"Les fibres","À quoi servent les fibres ?",
  "Ni absorbées ni inutiles : elles ralentissent, nourrissent, et remplissent.",
  ["Solubles et insolubles","L'effet sur la vitesse d'absorption",
   "Le seuil européen qui autorise la mention « source de fibres »"]),
 (7,"Les micronutriments","À quoi servent les vitamines et les minéraux ?",
  "Aucune énergie, mais rien ne fonctionne sans eux.",
  ["Ce qu'est un cofacteur","Les carences réelles en population française",
   "Pourquoi les compléments ne réparent pas une alimentation"]),
 (8,"L'eau","Quel rôle joue l'eau dans l'alimentation ?",
  "Elle porte le volume, donc la satiété, sans porter d'énergie.",
  ["La part d'eau des aliments courants","Volume sans calories",
   "Soif et faim : deux signaux souvent confondus"]),
 (9,"Une calorie, c'est quoi","Qu'est-ce qu'une calorie mesure exactement ?",
  "Une chaleur de combustion, mesurée hors du corps.",
  ["La bombe calorimétrique","Ce que l'unité décrit","Ce qu'elle ignore"]),
 (10,"Comment on compte les calories","D'où viennent les chiffres des étiquettes ?",
  "De coefficients moyens établis à la fin du XIXe siècle.",
  ["Atwater et les facteurs 4/9/4","Ce que ces moyennes lissent",
   "Pourquoi l'écart est nul sur une farine et fort sur une amande"]),
 (11,"Une calorie n'est pas une calorie","Pourquoi toutes les calories ne se valent pas ?",
  "Trois pertes séparent la chaleur mesurée de l'énergie réellement disponible.",
  ["Les coefficients sont des moyennes","La digestion a un coût",
   "La transformation déplace la mesure","Ce que la calorie mesure encore correctement"]),
 (12,"Densité énergétique","Pourquoi certains aliments rassasient plus à énergie égale ?",
  "Les calories par gramme déterminent le volume mangé pour une même énergie.",
  ["kcal par gramme : l'échelle réelle","Ce que les gens mangent à volume constant",
   "Grammes pour 100 kcal : le repère du livre"]),
 (13,"Volume et calories","Quelle place occupe réellement ce qu'on mange ?",
  "Un même apport peut tenir dans une cuillère ou remplir une assiette.",
  ["Comparaison à énergie égale","Le rôle de l'eau et des fibres",
   "Pourquoi le volume compte pour l'arrêt du repas"]),
 (14,"Le piège sucre et gras","Pourquoi la combinaison sucre-gras est-elle particulière ?",
  "Une association rare dans la nature, très efficace sur le circuit de récompense.",
  ["Ce que la nature associe rarement","L'effet sur la récompense",
   "Pourquoi la satiété arrive tard sur ces aliments"]),
 (15,"L'impact glycémique d'un aliment","Que fait un aliment à la glycémie ?",
  "L'indice glycémique, la charge, et ce que les deux ne disent pas.",
  ["Indice contre charge glycémique","Ce que change la cuisson et la matrice",
   "Les limites de la mesure hors contexte de repas"]),
 (16,"L'échelle de la transformation","Qu'est-ce qu'un aliment ultra-transformé ?",
  "Une classification par degré de transformation, et ce qu'elle prédit.",
  ["La classification NOVA et ses quatre groupes",
   "L'essai qui a mesuré 500 kcal d'écart par jour",
   "Ce que la transformation change à vitesse égale d'ingestion"]),
 (17,"Le sucre là où on ne le voit pas","Où se cache le sucre ajouté ?",
  "Les produits salés en contiennent souvent autant que les sucrés.",
  ["Les noms du sucre sur les étiquettes","Les catégories les plus concernées",
   "Sucres ajoutés et sucres naturellement présents"]),
 (18,"Les promesses des emballages","Que valent les mentions sur les emballages ?",
  "Les allégations sont encadrées, mais leur seuil légal surprend souvent.",
  ["Ce que « allégé », « source de », « riche en » exigent légalement",
   "Ce qu'une allégation ne dit pas du reste du produit"]),
 (19,"Pourquoi on n'arrête pas","Pourquoi est-il si difficile de s'arrêter devant certains aliments ?",
  "Densité, vitesse d'ingestion et texture court-circuitent le signal d'arrêt.",
  ["La vitesse d'ingestion contre le délai de satiété",
   "La texture qui n'oppose pas de résistance","L'absence de matrice à démonter"]),
 (20,"Les édulcorants","Les édulcorants sont-ils un allié ou un faux ami ?",
  "Ils retirent l'énergie sans retirer le goût sucré ; le débat porte sur la suite.",
  ["Ce qui est établi sur l'apport énergétique",
   "Ce qui est discuté : appétit, microbiote","L'état réel du consensus"]),
 (21,"Les faux ennemis","Quels aliments ont une mauvaise réputation imméritée ?",
  "Certains aliments accusés ne portent pas ce qu'on leur reproche.",
  ["Ce que disent les données sur les cas les plus cités",
   "D'où viennent ces réputations","Ce qui reste vrai malgré tout"]),
 (22,"Tableau — ingrédients courants 1","Que contiennent les ingrédients de base ?",
  "Comparaison ligne à ligne, portions réelles.",["Céréales, féculents, légumineuses"]),
 (23,"Tableau — ingrédients courants 2","Que contiennent les produits animaux ?",
  "Comparaison ligne à ligne, portions réelles.",["Viandes, poissons, œufs, produits laitiers"]),
 (24,"Tableau — ingrédients courants 3","Que contiennent fruits, légumes et matières grasses ?",
  "Comparaison ligne à ligne, portions réelles.",["Fruits, légumes, huiles, oléagineux"]),
 (25,"Tableau — plats courants 1","Que contient un plat complet ?",
  "Des plats entiers, pas des ingrédients isolés.",["Plats les plus consommés en France"]),
 (26,"Tableau — plats courants 2","Que contient un plat préparé ?",
  "Comparaison entre fait maison et préparé.",["Même plat, deux modes de préparation"]),
 (27,"Tableau — en-cas 1","Que contient ce qu'on mange entre les repas ?",
  "Les en-cas les plus courants, à portion réelle.",["Sucrés et salés côte à côte"]),
 (28,"Tableau — en-cas 2","Quel en-cas pour quelle situation ?",
  "Comparaison par densité et par volume.",["Classement par grammes pour 100 kcal"]),
 (29,"Récapitulatif de la partie","Que faut-il retenir de la composition des aliments ?",
  "Les six grandeurs qui décrivent un aliment mieux que son nombre de calories.",
  ["Les grandeurs à lire","Celles qui portent un verdict, celles qui décrivent"]),
]

PLAN[3] = [
 (1,"Le métabolisme, qu'est-ce que c'est","Qu'appelle-t-on le métabolisme ?",
  "L'ensemble de ce que le corps dépense, dont la plus grosse part ne se voit pas.",
  ["Ce que le mot recouvre réellement","Pourquoi « avoir un métabolisme lent » veut rarement dire ce qu'on croit"]),
 (2,"Le métabolisme de base","Combien le corps dépense-t-il sans rien faire ?",
  "La dépense au repos représente la majorité du total.",
  ["Ce que coûtent le cerveau, le foie, le cœur, les reins",
   "Ce qui le fait varier d'une personne à l'autre","La part de la masse maigre"]),
 (3,"Les quatre sources de dépense","Où part l'énergie dans une journée ?",
  "Métabolisme de base, digestion, mouvement involontaire, exercice — et leurs proportions réelles.",
  ["Les quatre postes et leur part","Ce qui surprend dans la répartition",
   "La seule part réellement pilotable au quotidien"]),
 (4,"L'effet thermique des aliments","Digérer coûte-t-il de l'énergie ?",
  "Assimiler consomme une part de ce qui est apporté, très variable selon le macronutriment.",
  ["20 à 30 % pour les protéines, 0 à 3 % pour les lipides",
   "Ce que cela change à apport égal"]),
 (5,"Le NEAT, le vrai brûleur","Quelle est la part du mouvement qu'on ne compte pas ?",
  "Tout ce qui bouge hors sport : la variable la plus large entre deux personnes.",
  ["Ce que recouvre le NEAT","L'écart entre deux personnes de même poids",
   "Pourquoi il baisse en restriction sans qu'on s'en aperçoive"]),
 (6,"L'exercice : la part variable","Combien une séance de sport brûle-t-elle vraiment ?",
  "Moins qu'annoncé, et rarement là où on l'attend.",
  ["Ce que brûle une heure d'activité, chiffres réels",
   "Ce que les machines de salle surestiment","Pourquoi l'intérêt du sport est ailleurs"]),
 (7,"Ce qui fait varier le métabolisme","Pourquoi deux personnes ne dépensent-elles pas pareil ?",
  "Masse maigre, âge, sexe, historique de régimes, température.",
  ["Les facteurs établis et leur poids relatif","Ce qui se modifie et ce qui ne se modifie pas"]),
 (8,"Récapitulatif de la partie","Que contrôle-t-on vraiment dans sa dépense ?",
  "Ce qui se pilote, ce qui s'influence, ce qui ne bouge pas.",
  ["Les trois catégories","Où porter l'effort si on ne peut en porter qu'un"]),
]

PLAN[4] = [
 (1,"Le muscle, c'est quoi","De quoi un muscle est-il fait ?",
  "Un tissu coûteux à entretenir, et c'est précisément son intérêt.",
  ["Fibres, types, et ce qu'elles consomment au repos",
   "Ce que pèse le muscle par rapport à la graisse à volume égal"]),
 (2,"Comment un muscle grossit","Que se passe-t-il quand un muscle se développe ?",
  "Un signal mécanique, une réparation, une adaptation.",
  ["La tension mécanique comme déclencheur","La synthèse protéique et sa fenêtre",
   "Pourquoi la croissance a lieu au repos, pas à l'effort"]),
 (3,"Les trois leviers de l'hypertrophie","De quoi dépend la prise de muscle ?",
  "Tension mécanique, volume, progression — le reste est secondaire.",
  ["Les trois leviers par ordre d'importance","Ce qui relève du détail"]),
 (4,"Volume, fréquence, intensité","Combien de séances, et de quelle intensité ?",
  "Les repères issus des méta-analyses, et leur marge.",
  ["Les séries hebdomadaires par groupe musculaire",
   "Ce que la fréquence change à volume égal","La marge réelle autour de ces chiffres"]),
 (5,"La récupération","Pourquoi le repos fait-il partie de l'entraînement ?",
  "L'adaptation se produit entre les séances, pas pendant.",
  ["Les délais de récupération par type d'effort",
   "Le rôle du sommeil dans la réparation","Le surentraînement : ce qu'il est vraiment"]),
 (6,"Protéines : combien, quand","Faut-il manger plus de protéines quand on s'entraîne ?",
  "Une fourchette, une répartition, et beaucoup de bruit autour.",
  ["Les apports établis par la littérature",
   "Ce que la répartition sur la journée change","Ce que la fenêtre anabolique n'est pas"]),
 (7,"Les suppléments","Quels compléments servent réellement ?",
  "Une poignée ont des preuves, le reste vit de marketing.",
  ["Ceux qui ont des données solides","Ceux qui n'en ont pas",
   "Ce qu'un supplément ne remplace jamais"]),
 (8,"Cardio ou musculation","Faut-il choisir entre cardio et musculation ?",
  "Deux effets différents, souvent opposés à tort.",
  ["Ce que chacun produit","Ce qu'ils produisent ensemble",
   "Pourquoi la question est mal posée"]),
 (9,"Ce que brûle une séance","Combien de calories une séance dépense-t-elle ?",
  "Le chiffre affiché, le chiffre réel, et ce qui se passe après.",
  ["Les valeurs réelles par activité","L'effet après l'effort et sa taille véritable",
   "La compensation involontaire dans le reste de la journée"]),
 (10,"Tableau — sports d'endurance","Que produit chaque sport d'endurance ?",
  "Comparaison des activités cardio.",["Dépense, impact, muscles sollicités"]),
 (11,"Tableau — sports de force et mixtes","Que produit chaque sport de force ?",
  "Comparaison des activités de force et mixtes.",["Dépense, impact, muscles sollicités"]),
 (12,"Tableau — activités douces","Que produisent les activités douces ?",
  "Comparaison des activités de faible intensité.",["Dépense, souplesse, accessibilité"]),
 (13,"Les mythes du sport","Quelles idées reçues sur le sport sont fausses ?",
  "Localiser la perte, transformer le gras en muscle, la zone brûle-graisse.",
  ["Ce que dit la physiologie sur chaque idée reçue","D'où viennent ces croyances"]),
 (14,"Pourquoi la majorité abandonne","Pourquoi arrête-t-on le sport ?",
  "Les causes d'abandon sont documentées, et elles ne sont pas la motivation.",
  ["Les causes réelles d'arrêt","Le seuil d'effort qui ne tient pas dans une semaine ordinaire",
   "Ce que « manquer de motivation » recouvre"]),
 (15,"Une minute vaut mieux que zéro","Un effort minime sert-il à quelque chose ?",
  "L'écart le plus grand se situe entre zéro et un peu, pas entre beaucoup et un peu plus.",
  ["La courbe des bénéfices : la pente est au début",
   "Ce que produisent quelques minutes quotidiennes","Pourquoi le tout ou rien fait perdre le tout"]),
 (16,"Construire une routine qui tient","Comment installer une pratique durable ?",
  "Une pratique qui dure se conçoit sur ses contraintes, pas sur ses ambitions.",
  ["Le rôle de la fréquence contre l'intensité",
   "Ce qui rend une séance reproductible","Le plancher plutôt que le plafond"]),
 (17,"Pourquoi on stagne","Pourquoi les progrès s'arrêtent-ils ?",
  "L'adaptation rend efficace, donc moins coûteux.",
  ["Le principe de surcharge progressive","Les paliers normaux",
   "Ce qui distingue une stagnation d'un plateau réel"]),
 (18,"Récapitulatif de la partie","Que retenir sur le muscle et le mouvement ?",
  "Ce que le sport produit vraiment, et à quelle échéance.",
  ["Effets immédiats, effets à un an","La hiérarchie des leviers"]),
]

PLAN[5] = [
 (1,"Le terrain caché, c'est quoi","Qu'est-ce qui agit sans passer par l'assiette ?",
  "Sommeil, stress, alcool, lumière, âge : des facteurs qui modifient la faim et la dépense.",
  ["Pourquoi ces facteurs sont rarement comptés","Leur poids réel comparé à l'alimentation"]),
 (2,"Le sommeil","Que fait le sommeil au métabolisme ?",
  "Une nuit courte modifie les hormones de la faim dès le lendemain.",
  ["Ce que la privation de sommeil fait à la ghréline et à la leptine",
   "L'effet mesuré sur la prise alimentaire du lendemain","Les besoins réels en durée"]),
 (3,"Mal dormir et prise de poids","Le manque de sommeil fait-il grossir ?",
  "Les essais contrôlés montrent un effet, et son mécanisme est identifié.",
  ["Ce que montrent les essais en laboratoire","La part attribuable au grignotage nocturne",
   "Ce qui reste corrélation et ce qui est causal"]),
 (4,"Mieux dormir dès ce soir","Que peut-on changer pour mieux dormir ?",
  "Quelques facteurs ont des preuves solides, beaucoup n'en ont pas.",
  ["Lumière, température, horaires, caféine","Ce qui a des preuves et ce qui relève du rituel"]),
 (5,"Le stress qui fait stocker","Le stress fait-il grossir ?",
  "Il agit par deux voies : hormonale et comportementale.",
  ["La voie du cortisol","La voie du comportement alimentaire",
   "Laquelle pèse le plus dans les faits"]),
 (6,"Le cortisol","Que fait vraiment le cortisol ?",
  "Une hormone nécessaire, accusée au-delà de ce qu'elle fait.",
  ["Son rôle normal dans la journée","Ce qu'un excès chronique produit",
   "Ce qu'on lui attribue à tort"]),
 (7,"Faire baisser son stress","Que peut-on faire contre le stress, réellement ?",
  "Les interventions testées, avec leur effet mesuré.",
  ["Ce qui a été mesuré en essai","L'écart entre efficacité et faisabilité"]),
 (8,"L'inflammation silencieuse","Qu'est-ce que l'inflammation de bas grade ?",
  "Un état discret, mesurable, associé à beaucoup de choses.",
  ["Ce qu'on mesure et comment","Ce qui l'entretient",
   "La prudence nécessaire sur les liens de causalité"]),
 (9,"Manger anti-inflammatoire","Peut-on réduire l'inflammation par l'alimentation ?",
  "Certains schémas alimentaires ont un effet mesuré ; les aliments miracles n'existent pas.",
  ["Ce que montrent les schémas alimentaires étudiés",
   "Pourquoi aucun aliment isolé ne suffit"]),
 (10,"L'intestin parle au cerveau","L'intestin influence-t-il l'humeur et l'appétit ?",
  "Un axe de communication réel, largement surinterprété.",
  ["Les voies de communication établies","Ce que les études animales ne prouvent pas chez l'humain",
   "L'état honnête du savoir"]),
 (11,"La lumière","La lumière change-t-elle quelque chose au métabolisme ?",
  "Elle règle l'horloge interne, qui règle beaucoup de choses.",
  ["Lumière du matin et calage de l'horloge","Lumière du soir et endormissement"]),
 (12,"Bouger toute la journée","Faut-il bouger plus, ou s'entraîner plus ?",
  "L'activité diffuse pèse davantage que la séance dans la dépense totale.",
  ["Le NEAT appliqué au quotidien","Ce que la position assise prolongée modifie"]),
 (13,"Le lien social","Le contexte social influence-t-il ce qu'on mange ?",
  "La présence des autres modifie la quantité mangée, de façon mesurée.",
  ["L'effet de facilitation sociale","Ce que l'isolement change"]),
 (14,"L'alcool","Que fait l'alcool au corps ?",
  "Une énergie prioritaire qui suspend le reste.",
  ["7 kcal par gramme, et le foie qui traite en priorité",
   "Ce que la lipolyse fait pendant ce temps","L'effet sur le sommeil et sur l'appétit"]),
 (15,"Le jeûne intermittent","Le jeûne intermittent apporte-t-il quelque chose ?",
  "Un cadre horaire dont l'effet propre reste discuté à apport égal.",
  ["Les protocoles courants","Ce que les essais montrent à apport égal",
   "L'autophagie : ce qui est établi chez l'humain"]),
 (16,"L'eau : soif, faim, rétention","Combien faut-il boire, et pourquoi ?",
  "Les besoins réels, la confusion soif-faim, et la rétention mal comprise.",
  ["Les apports de référence","Pourquoi la rétention n'est pas de la graisse",
   "Le rôle des électrolytes"]),
 (17,"Vieillir","Qu'est-ce qui change après quarante ans ?",
  "La masse maigre baisse, la dépense suit, les besoins changent.",
  ["La sarcopénie et son rythme","Ce qui ralentit vraiment, et de combien",
   "Ce qui reste modifiable"]),
 (18,"Le corps féminin","En quoi le métabolisme féminin diffère-t-il ?",
  "Cycle hormonal, composition corporelle, et des recommandations souvent calquées sur les hommes.",
  ["Ce que le cycle modifie sur la dépense et l'appétit",
   "Les différences de composition corporelle","Ce que la recherche a longtemps ignoré"]),
 (19,"Récapitulatif de la partie","Que retenir du terrain ?",
  "Les causes d'échec qui ne se trouvent pas dans l'assiette.",
  ["Les facteurs par poids décroissant","Ceux sur lesquels agir en premier"]),
]

PLAN[6] = [
 (1,"Rien à supprimer","Faut-il supprimer des aliments pour perdre du poids ?",
  "L'interdiction crée l'envie et prépare l'abandon.",
  ["Ce que produit une restriction cognitive",
   "Pourquoi les listes d'interdits échouent","Ce que remplacer veut dire"]),
 (2,"Comment une perte se provoque","Qu'est-ce qui fait perdre du poids ?",
  "Un déficit énergétique, quelle que soit la manière dont il est obtenu.",
  ["Le principe, et pourquoi il n'est pas contestable",
   "Les nombreuses façons de l'obtenir","Ce que ce principe ne dit pas"]),
 (3,"Le déficit : combien, combien de temps","Quelle taille de déficit, et sur quelle durée ?",
  "Un déficit trop grand se paie ; un déficit petit se tient.",
  ["Les ordres de grandeur","Ce qu'un déficit trop fort déclenche",
   "Le rythme de perte que la littérature juge tenable"]),
 (4,"Le corps qui résiste","Pourquoi la perte ralentit-elle toujours ?",
  "Le corps s'adapte : il dépense moins et réclame plus.",
  ["La baisse du métabolisme au-delà de la perte de masse",
   "La baisse du NEAT, involontaire et invisible","La hausse de la faim"]),
 (5,"Le set-point","Le corps a-t-il un poids qu'il défend ?",
  "Une zone défendue plutôt qu'un point, et défendue plus fort vers le bas.",
  ["Ce que le modèle explique","Ce qu'il n'explique pas",
   "Pourquoi la défense est asymétrique"]),
 (6,"L'effet yoyo","Pourquoi reprend-on plus qu'on n'avait perdu ?",
  "Les adaptations survivent à la perte et facilitent la reprise.",
  ["Ce qui persiste après le retour au poids initial",
   "Les données de suivi à long terme","Ce que chaque cycle laisse"]),
 (7,"La lutte et l'abandon","Pourquoi la volonté ne suffit-elle pas ?",
  "Un effort qui demande de lutter en permanence a une date d'expiration.",
  ["Ce que coûte la vigilance permanente",
   "Le moment de bascule vers l'abandon","Pourquoi ce n'est pas un défaut de caractère"]),
 (8,"Cinq kilos par an","Vaut-il mieux perdre lentement ?",
  "Une perte lente et définitive dépasse une perte rapide reprise.",
  ["La comparaison sur cinq ans","Ce que la vitesse coûte en masse maigre",
   "Le calcul qu'on ne fait jamais"]),
 (9,"Maintenir","Comment garde-t-on un poids une fois atteint ?",
  "La phase la moins étudiée, la plus longue, et celle qui décide de tout.",
  ["Ce que font les personnes qui maintiennent",
   "Pourquoi maintenir demande autre chose que perdre"]),
 (10,"Du savoir au réflexe","Comment passe-t-on de comprendre à faire ?",
  "Ce qui devient automatique cesse de demander de la volonté.",
  ["Le rôle du contexte contre celui de la décision",
   "Les changements qui ne demandent pas d'arbitrage quotidien"]),
 (11,"L'assiette équilibrée","À quoi ressemble une assiette équilibrée ?",
  "Un repère visuel qui remplace le comptage.",
  ["Les proportions et leur justification","Pourquoi un visuel tient mieux qu'un chiffre"]),
 (12,"Une portion, c'est combien","Comment évaluer une portion sans balance ?",
  "Des repères corporels, transportables partout.",
  ["Les repères à la main","Leur marge d'erreur réelle"]),
 (13,"Adapter son assiette","Comment ajuster selon son objectif ?",
  "Les mêmes proportions, déplacées.",
  ["Ce qui bouge selon l'objectif","Ce qui ne bouge jamais"]),
 (14,"Le petit-déjeuner","Que vaut un petit-déjeuner, et faut-il en prendre un ?",
  "Ce que la composition change sur la matinée.",
  ["Sucré contre protéiné : l'effet sur la faim de 11 h",
   "Ce que dit la littérature sur le sauter"]),
 (15,"Le déjeuner","Comment composer un déjeuner qui tient l'après-midi ?",
  "La composition décide de l'heure du prochain creux.",
  ["Ce qui prolonge la satiété","Le rôle de l'ordre des aliments"]),
 (16,"Le dîner","Le dîner doit-il être léger ?",
  "Ce que l'heure et la composition changent sur la nuit.",
  ["L'effet sur le sommeil","Ce que « léger » veut dire concrètement"]),
 (17,"Le creux de dix-sept heures","Pourquoi a-t-on faim en fin d'après-midi ?",
  "Un creux prévisible, dont la cause se trouve au repas précédent.",
  ["Le mécanisme du creux","Ce qui l'a préparé plusieurs heures avant"]),
 (18,"Grignoter mieux","S'il faut grignoter, comment le faire ?",
  "À énergie égale, tous les en-cas ne se valent pas.",
  ["Le classement par densité et par volume","Ce qui tient jusqu'au repas"]),
 (19,"Les faux amis du quotidien","Quels aliments réputés sains ne le sont pas ?",
  "Jus, barres de céréales, produits allégés, yaourts aux fruits.",
  ["Les cas les plus courants, chiffres à l'appui","Ce qui crée l'illusion"]),
 (20,"Au restaurant","Comment décider au restaurant ?",
  "Une grille de lecture qui tient sans calcul.",
  ["Les questions à se poser sur une carte","Ce qui change le plus pour le moins d'effort"]),
 (21,"Le classement des fast-foods","Que vaut vraiment un repas de fast-food ?",
  "Comparaison des chaînes et des menus, à portion réelle.",
  ["Le classement par densité énergétique","Les écarts à l'intérieur d'une même enseigne"]),
 (22,"Le bar et l'alcool","Comment l'alcool s'ajoute-t-il au reste ?",
  "L'énergie liquide s'ajoute sans rassasier, et lève les freins.",
  ["Les valeurs par verre","L'effet sur ce qui est mangé ensuite"]),
 (23,"Faire ses courses","Comment les courses décident du reste de la semaine ?",
  "Ce qui entre chez soi détermine ce qui sera mangé.",
  ["Le choix se fait au magasin, pas devant le placard",
   "Ce que l'agencement des rayons exploite"]),
 (24,"Nourrir ses enfants","Comment nourrir un enfant sans lui transmettre le problème ?",
  "Les préférences se forment tôt, et les interdits se retournent.",
  ["Ce que l'exposition répétée produit","Pourquoi interdire renforce l'attrait",
   "Le rôle de l'exemple contre celui de la consigne"]),
 (25,"Ce livre ne dit pas quoi faire","Que faire de tout cela ?",
  "Le livre s'arrête où la décision commence.",
  ["Ce qui a été décrit","Ce qui appartient au lecteur, et pourquoi"]),
]
