# -*- coding: utf-8 -*-
"""
Le plan du livre — neuf parties (0 à 8), chacune une question du lecteur.

Les parties 5 et 6 sont les deux échecs en miroir — l'assiette, l'effort —,
la 7 examine les aides en escalade (médicaments, chirurgie, dopage) sans
les juger, et la 8 est la réponse durable. Les compléments restent en
partie 4, avec l'entraînement. Les sous-titres des parties
(content/parts.ts) portent le retournement vers le second public.

Règle des titres : jamais l'organe ni le jargon, toujours la question vécue.
"""

# (ordre, titre, question, resume, [idées])
PLAN = {
0: [
 (1,"Pourquoi ce livre","Pourquoi un livre de plus sur l'alimentation ?",
  "La documentation disponible prescrit ou reste illisible ; presque rien n'explique le mécanisme.",
  ["Deux familles de sources : les instructions, et la recherche illisible hors de sa discipline", "L'espace vide entre les deux : ce qui se passe à l'intérieur du corps", "Ce livre décrit, il ne prescrit pas — la décision appartient au lecteur"]),
 (2,"Comment lire ce livre","Comment lire ce livre ?",
  "Chaque double page se suffit à elle-même et répond à une question.",
  ["Lecture dans l'ordre ou par entrées séparées", "Une double page = une question = un mécanisme", "Les renvois nomment les notions empruntées aux autres pages"]),
 (3,"Promesse et limites","Que peut ce livre, et que ne peut-il pas ?",
  "Il explique des mécanismes ; il ne remplace ni un médecin ni un diagnostic.",
  ["Aucun chiffre présenté comme un objectif", "Aucune donnée sans sa source", "Les mécanismes sont décrits avec leurs limites et leurs débats ouverts", "Ce qui relève du médecin y reste"]),
 (4,"Sommaire visuel","De quoi ce livre parle-t-il, en une image ?",
  "Le plan du livre en une planche, huit questions qui s'enchaînent.",
  ["Les six questions et leur enchaînement", "Ce que le lecteur sait faire au sortir de chacune"]),
],
1: [
 (1,"La faim à heure fixe","Pourquoi a-t-on faim à heure fixe ?",
  "La faim n'attend pas le réservoir vide : elle anticipe les repas habituels.",
  ["La ghréline monte avant les repas habitués, pas quand les réserves baissent", "Ce qui se passe quand on ignore le signal : il redescend", "La faim programmée n'est pas la faim du besoin"]),
 (2,"Les hormones de la faim","Qu'est-ce qui déclenche la sensation de faim ?",
  "Deux messagers principaux : l'un appelle, l'autre informe des réserves.",
  ["Ghréline : le signal montant", "Leptine : le niveau des réserves, et la résistance à son signal", "Pourquoi le signal des réserves se dérègle avec le surpoids"]),
 (3,"Faim ou envie","La faim et l'envie de manger sont-elles la même chose ?",
  "Deux circuits distincts : le besoin et la récompense.",
  ["Le circuit homéostatique et le circuit du plaisir", "Avoir envie sans avoir faim : le dessert après un repas complet", "Ce que la vue et l'odeur déclenchent à elles seules"]),
 (4,"Faim malgré l'estomac plein","Pourquoi peut-on avoir faim l'estomac plein ?",
  "Le volume n'est qu'un des signaux, et pas le plus durable.",
  ["Les capteurs de la paroi gastrique et leur délai", "La vidange : un liquide part vite, un solide reste", "Pourquoi un repas bu ne cale pas comme un repas mâché"]),
 (5,"Le signal d'arrêt","Qu'est-ce qui fait qu'on arrête de manger ?",
  "Trois signaux successifs : le volume, les hormones intestinales, puis les réserves.",
  ["Le volume gastrique, immédiat", "Les hormones intestinales, en vingt minutes", "La densité énergétique : le déterminant le mieux étayé de la satiété"]),
 (6,"Manger vite, manger trop","Pourquoi mange-t-on trop quand on mange vite ?",
  "Le signal d'arrêt met vingt minutes ; un repas rapide le prend de vitesse.",
  ["Le délai incompressible des signaux intestinaux", "Ce que les essais mesurent quand on impose la lenteur", "La texture qui ne demande pas de mastication"]),
 (7,"Les aliments dont on ne s'arrête pas","Pourquoi certains aliments font-ils perdre le contrôle ?",
  "Densité, texture et sucre-gras court-circuitent le signal d'arrêt.",
  ["La vitesse d'ingestion contre le délai de satiété", "L'absence de matrice à démonter", "Ce que l'industrie optimise réellement"]),
 (8,"La glycémie et les fringales","Pourquoi a-t-on une fringale deux heures après un repas sucré ?",
  "Un pic appelle une descente, et la descente appelle la suite.",
  ["Le pic, la réponse insulinique, le creux réactionnel", "Pourquoi la fringale réclame du sucre et pas du brocoli", "Ce qui amortit la courbe : fibres, protéines, matrice"]),
 (9,"Mal dormir donne faim","Pourquoi a-t-on plus faim après une nuit courte ?",
  "Une nuit écourtée modifie les hormones de la faim dès le lendemain.",
  ["Ghréline en hausse, leptine en baisse : les essais en laboratoire", "L'effet mesuré sur la prise alimentaire du lendemain", "Pourquoi la fatigue oriente vers le dense et le sucré"]),
 (10,"Le stress qui fait manger","Pourquoi mange-t-on plus quand on est stressé ?",
  "Deux voies : l'hormonale et la comportementale — et la seconde pèse lourd.",
  ["La voie du cortisol", "Manger comme réponse apprise au stress", "Pourquoi le stress choisit rarement une pomme"]),
 (11,"Soif ou faim","Peut-on confondre la soif et la faim ?",
  "Les deux signaux se ressemblent assez pour se tromper de réponse.",
  ["Ce que les deux sensations partagent", "Le test simple du verre d'eau", "La part d'eau des aliments, et ce qu'elle change au volume"]),
 (12,"L'heure interne","Pourquoi l'heure des repas compte-t-elle ?",
  "L'horloge interne règle la faim, et aussi ce que le corps fait du repas.",
  ["L'horloge centrale et les horloges des organes", "La tolérance au glucose qui varie au fil de la journée", "Ce que la science établit et ce qu'elle discute encore"]),
 (13,"Quand la faim manque","Pourquoi certains n'ont-ils jamais faim ?",
  "Le signal peut s'éteindre autant qu'il peut s'emballer.",
  ["Le stress aigu coupe la faim quand le stress chronique la nourrit", "Petits mangeurs : des signaux de satiété plus précoces, pas un défaut", "Pourquoi sauter des repas éteint le signal au lieu de l'aiguiser"]),
 (14,"Récapitulatif — lire ses signaux","Comment distinguer le besoin, l'envie et l'habitude ?",
  "Les signaux de la partie, réunis en une grille de lecture.",
  ["Les trois origines d'une envie de manger", "Les indices qui les distinguent", "Ce qu'on peut observer chez soi dès aujourd'hui"]),
],
2: [
 (1,"Manger, c'est quoi","Qu'est-ce que le corps reçoit vraiment quand on mange ?",
  "Un repas apporte de la matière et, en même temps, un jeu de signaux.",
  ["La matière : ce que mesure l'étiquette", "Les signaux : ce qui décide de l'usage", "Pourquoi deux repas identiques en calories ne se valent pas"]),
 (2,"Le voyage d'une bouchée","Où va un aliment après la première bouchée ?",
  "Le trajet complet, de la mastication au tissu adipeux, en une planche.",
  ["Les étapes et leurs durées réelles", "Où chaque macronutriment est absorbé", "Ce que le corps prélève, ce qu'il laisse passer"]),
 (3,"Mâcher change tout","Pourquoi la mastication change-t-elle ce que le corps absorbe ?",
  "La bouche démonte la matrice, et le degré de démontage règle la suite.",
  ["L'amylase salivaire attaque l'amidon dès la bouche", "Matrice intacte contre matrice broyée : la pomme, la compote, le jus", "La phase céphalique : le corps se prépare avant que rien n'arrive"]),
 (4,"Ce qui échappe au corps","Le corps absorbe-t-il tout ce qu'on avale ?",
  "Presque tout, mais pas tout — et l'écart dépend de l'aliment.",
  ["La surface d'absorption réelle de l'intestin", "Le cas des amandes : un quart de l'énergie traverse", "Fibres et matrices : ce qui protège de l'absorption"]),
 (5,"La part du microbiote","Que font les bactéries de l'intestin de ce qu'on mange ?",
  "Elles digèrent ce que le corps ne sait pas digérer, et produisent des molécules actives.",
  ["Les fibres fermentées en acides gras à chaîne courte", "Ce que le microbiote extrait en plus des étiquettes", "Ce qui est établi et ce qui reste spéculatif"]),
 (6,"Le glucose et l'insuline","Qui décide si le sucre est brûlé ou stocké ?",
  "L'insuline ouvre les portes des cellules et fixe l'ordre d'utilisation.",
  ["La glycémie monte, l'insuline répond, la glycémie redescend", "Le glycogène d'abord, le reste ensuite", "Ce que veut dire « pic » et ce que ça ne veut pas dire"]),
 (7,"Le stockage","Comment le corps met-il l'énergie de côté ?",
  "Deux réserves de tailles très inégales : le glycogène et le tissu adipeux.",
  ["Le glycogène : petit, rapide, saturé vite", "Le tissu adipeux : quasi illimité", "Les trois routes qui mènent au gras"]),
 (8,"Le déstockage","À quelle condition le corps puise-t-il dans ses réserves ?",
  "Il faut une baisse de l'insuline et un besoin non couvert.",
  ["Ce qui autorise la lipolyse", "Pourquoi elle s'arrête dès qu'un apport arrive", "L'alternance quotidienne stockage / déstockage"]),
 (9,"Une calorie, c'est quoi","Qu'est-ce qu'une calorie mesure exactement ?",
  "Une chaleur de combustion, mesurée hors du corps.",
  ["La bombe calorimétrique", "Ce que l'unité décrit", "Ce qu'elle ignore"]),
 (10,"Comment on compte les calories","D'où viennent les chiffres des étiquettes ?",
  "De coefficients moyens établis à la fin du XIXe siècle.",
  ["Atwater et les facteurs 4/9/4", "Ce que ces moyennes lissent", "Pourquoi l'écart est nul sur une farine et fort sur une amande"]),
 (11,"Une calorie n'est pas une calorie","Pourquoi toutes les calories ne se valent pas ?",
  "Trois pertes séparent la chaleur mesurée de l'énergie réellement disponible.",
  ["Les coefficients sont des moyennes", "La digestion a un coût", "La transformation déplace la mesure", "Ce que la calorie mesure encore correctement"]),
 (12,"Les calories qu'on ne voit pas passer","Comment avale-t-on 500 kcal sans s'en apercevoir ?",
  "La densité énergétique décide de ce qu'un même geste de manger apporte.",
  ["kcal par gramme : l'échelle réelle, de la carotte à l'huile", "À volume mangé constant, l'énergie varie du simple au décuple", "Grammes pour 100 kcal : le repère du livre"]),
 (13,"Volume et calories","Quelle place occupe réellement ce qu'on mange ?",
  "Un même apport peut tenir dans une cuillère ou remplir une assiette.",
  ["Comparaison à énergie égale", "Le rôle de l'eau et des fibres", "Pourquoi le volume compte pour l'arrêt du repas"]),
 (14,"Le piège sucre et gras","Pourquoi la combinaison sucre-gras est-elle si redoutable ?",
  "Une association rare dans la nature, très efficace sur le circuit de récompense.",
  ["Ce que la nature associe rarement", "L'effet sur la récompense", "Pourquoi la satiété arrive tard sur ces aliments"]),
 (15,"L'échelle de la transformation","Que change un aliment ultra-transformé ?",
  "À composition affichée égale, la transformation fait manger davantage.",
  ["La classification NOVA et ses quatre groupes", "L'essai qui a mesuré 500 kcal d'écart par jour", "Vitesse d'ingestion, texture, densité : les mécanismes de l'écart"]),
 (16,"L'alcool","Que fait l'alcool au stockage ?",
  "Une énergie prioritaire qui suspend le déstockage le temps de son passage.",
  ["7 kcal par gramme, et le foie qui traite en priorité", "Ce que la lipolyse fait pendant ce temps", "L'effet sur l'appétit du reste de la soirée"]),
 (17,"La détox n'existe pas, le foie si","Le corps a-t-il besoin d'être détoxifié ?",
  "Deux organes font ce travail en continu ; aucune cure ne s'y substitue.",
  ["Ce que le foie transforme réellement", "Ce que les reins filtrent et éliminent", "Pourquoi les cures détox n'ont pas de cible physiologique"]),
 (18,"Ceux qui ne grossissent jamais","Pourquoi certains mangent-ils beaucoup sans grossir ?",
  "Mesuré en laboratoire, le « gros mangeur qui ne grossit pas » mange moins ou dépense plus qu'il ne croit.",
  ["La sous-estimation des apports, mesurée à l'eau doublement marquée", "Le NEAT qui monte avec l'excès : la dépense qui s'ajuste toute seule", "La part de la génétique, honnêtement", "Ce que ça implique pour celui qui veut prendre du poids"]),
 (19,"Récapitulatif — les routes du stockage","Comment le surplus devient-il du gras, en résumé ?",
  "Le circuit complet, et les trois points où une décision agit.",
  ["Le trajet en une planche", "Les trois leviers réels sur ce trajet"]),
],
3: [
 (1,"Les trois macronutriments","Que sont les protéines, les glucides et les lipides ?",
  "Trois familles, trois rôles, trois destins différents dans le corps.",
  ["Ce que chacun construit, alimente ou met en réserve", "Les proportions dans une alimentation courante", "Ce qu'aucun ne remplace"]),
 (2,"Protéines : les briques","À quoi servent les protéines ?",
  "Elles construisent et réparent ; le corps n'en fait pas de réserve.",
  ["Acides aminés essentiels et non essentiels", "Pourquoi il n'existe pas de stock de protéines", "L'effet thermique le plus élevé des trois macros"]),
 (3,"Glucides : le carburant","À quoi servent les glucides ?",
  "Le carburant le plus rapide, et le seul dont le cerveau dépend directement.",
  ["Simples et complexes : une distinction qui vieillit mal", "Le glycogène, réserve courte", "Ce qui se passe quand elle est pleine"]),
 (4,"Lipides : la réserve","À quoi servent les lipides ?",
  "Densité énergétique maximale, rôle structurel, et une mauvaise réputation à nuancer.",
  ["9 kcal par gramme : pourquoi", "Saturés, insaturés, trans : ce qui les sépare", "Le rôle dans les membranes et les hormones"]),
 (5,"Les fibres","À quoi servent les fibres ?",
  "Ni absorbées ni inutiles : elles ralentissent, nourrissent, et remplissent.",
  ["Solubles et insolubles", "L'effet sur la vitesse d'absorption", "Le seuil européen qui autorise la mention « source de fibres »"]),
 (6,"Les micronutriments","À quoi servent les vitamines et les minéraux ?",
  "Aucune énergie, mais rien ne fonctionne sans eux.",
  ["Ce qu'est un cofacteur", "Les carences réelles en population française", "Pourquoi les compléments ne réparent pas une alimentation"]),
 (7,"L'eau dans l'assiette","Quel rôle joue l'eau dans l'alimentation ?",
  "Elle porte le volume, donc la satiété, sans porter d'énergie.",
  ["La part d'eau des aliments courants", "Volume sans calories", "Les besoins réels, et la rétention qui n'est pas de la graisse"]),
 (8,"L'impact glycémique d'un aliment","Que fait un aliment à la glycémie ?",
  "L'indice glycémique, la charge, et ce que les deux ne disent pas.",
  ["Indice contre charge glycémique", "Ce que change la cuisson et la matrice", "Les limites de la mesure hors contexte de repas"]),
 (9,"Le sucre là où on ne le voit pas","Où se cache le sucre ajouté ?",
  "Les produits salés en contiennent souvent autant que les sucrés.",
  ["Les noms du sucre sur les étiquettes", "Les catégories les plus concernées", "Sucres ajoutés et sucres naturellement présents"]),
 (10,"Les promesses des emballages","Que valent les mentions sur les emballages ?",
  "Les allégations sont encadrées, mais leur seuil légal surprend souvent.",
  ["Ce que « allégé », « source de », « riche en » exigent légalement", "Ce qu'une allégation ne dit pas du reste du produit"]),
 (11,"Les édulcorants","Les édulcorants sont-ils un allié ou un piège ?",
  "Ils retirent l'énergie sans retirer le goût sucré ; le débat porte sur la suite.",
  ["Ce qui est établi sur l'apport énergétique", "Ce qui est discuté : appétit, microbiote", "L'état réel du consensus"]),
 (12,"Les faux ennemis","Quels aliments ont une mauvaise réputation imméritée ?",
  "Certains aliments accusés ne portent pas ce qu'on leur reproche.",
  ["Ce que disent les données sur les cas les plus cités", "D'où viennent ces réputations", "Ce qui reste vrai malgré tout"]),
 (13,"Tableau — ingrédients courants 1","Que contiennent les ingrédients de base ?",
  "Comparaison ligne à ligne, portions réelles.",
  ["Céréales, féculents, légumineuses"]),
 (14,"Tableau — ingrédients courants 2","Que contiennent les produits animaux ?",
  "Comparaison ligne à ligne, portions réelles.",
  ["Viandes, poissons, œufs, produits laitiers"]),
 (15,"Tableau — ingrédients courants 3","Que contiennent fruits, légumes et matières grasses ?",
  "Comparaison ligne à ligne, portions réelles.",
  ["Fruits, légumes, huiles, oléagineux"]),
 (16,"Tableau — plats courants 1","Que contient un plat complet ?",
  "Des plats entiers, pas des ingrédients isolés.",
  ["Plats les plus consommés en France"]),
 (17,"Tableau — plats courants 2","Que contient un plat préparé ?",
  "Comparaison entre fait maison et préparé.",
  ["Même plat, deux modes de préparation"]),
 (18,"Tableau — en-cas 1","Que contient ce qu'on mange entre les repas ?",
  "Les en-cas les plus courants, à portion réelle.",
  ["Sucrés et salés côte à côte"]),
 (19,"Tableau — en-cas 2","Quel en-cas pour quelle situation ?",
  "Comparaison par densité et par volume.",
  ["Classement par grammes pour 100 kcal"]),
 (20,"Récapitulatif — lire un aliment","Que faut-il regarder avant le nombre de calories ?",
  "Les six grandeurs qui décrivent un aliment mieux que son étiquette énergétique.",
  ["Les grandeurs à lire", "Celles qui portent un verdict, celles qui décrivent"]),
],
4: [
 (1,"Le métabolisme, qu'est-ce que c'est","Qu'appelle-t-on le métabolisme ?",
  "L'ensemble de ce que le corps dépense, dont la plus grosse part ne se voit pas.",
  ["Ce que le mot recouvre réellement", "Pourquoi « avoir un métabolisme lent » veut rarement dire ce qu'on croit"]),
 (2,"Le métabolisme de base","Combien le corps dépense-t-il sans rien faire ?",
  "La dépense au repos représente la majorité du total.",
  ["Ce que coûtent le cerveau, le foie, le cœur, les reins", "Ce qui le fait varier d'une personne à l'autre", "La part de la masse maigre"]),
 (3,"Les quatre postes de dépense","Où part l'énergie dans une journée ?",
  "Base, digestion, mouvement involontaire, exercice — et leurs proportions réelles.",
  ["Les quatre postes et leur part", "Ce qui surprend dans la répartition", "La seule part réellement pilotable au quotidien"]),
 (4,"Digérer coûte de l'énergie","La digestion dépense-t-elle des calories ?",
  "Assimiler consomme une part de l'apport, très variable selon le macronutriment.",
  ["20 à 30 % pour les protéines, 0 à 3 % pour les lipides", "Ce que cela change à apport égal"]),
 (5,"Le NEAT, le vrai brûleur","Quelle est la part du mouvement qu'on ne compte pas ?",
  "Tout ce qui bouge hors sport : la variable la plus large entre deux personnes.",
  ["Ce que recouvre le NEAT", "L'écart entre deux personnes de même poids", "Pourquoi il baisse en restriction sans qu'on s'en aperçoive"]),
 (6,"Ce que brûle vraiment une séance","Combien de calories une séance de sport dépense-t-elle ?",
  "Moins qu'annoncé, et rarement là où on l'attend.",
  ["Ce que brûle une heure d'activité, chiffres réels", "Ce que les machines de salle surestiment", "La compensation involontaire du reste de la journée"]),
 (7,"Ce qui fait varier le métabolisme","Pourquoi deux personnes ne dépensent-elles pas pareil ?",
  "Masse maigre, âge, sexe, historique de régimes, température.",
  ["Les facteurs établis et leur poids relatif", "Ce qui se modifie et ce qui ne se modifie pas"]),
 (8,"Le muscle, la dépense qui dort","Pourquoi le muscle dépense-t-il même au repos ?",
  "Un tissu coûteux à entretenir — c'est précisément son intérêt.",
  ["Ce que consomme un kilo de muscle au repos, chiffres honnêtes", "Muscle et graisse à volume égal", "Pourquoi c'est le seul poste qu'on peut agrandir"]),
 (9,"Comment un muscle grossit","Que se passe-t-il quand un muscle se développe ?",
  "Un signal mécanique, une réparation, une adaptation.",
  ["La tension mécanique comme déclencheur", "La synthèse protéique et sa fenêtre", "Pourquoi la croissance a lieu au repos, pas à l'effort"]),
 (10,"Les trois leviers de l'hypertrophie","De quoi dépend la prise de muscle ?",
  "Tension mécanique, volume, progression — le reste est secondaire.",
  ["Les trois leviers par ordre d'importance", "Ce qui relève du détail"]),
 (11,"Volume, fréquence, intensité","Combien de séances, et de quelle intensité ?",
  "Les repères issus des méta-analyses, et leur marge.",
  ["Les séries hebdomadaires par groupe musculaire", "Ce que la fréquence change à volume égal", "La marge réelle autour de ces chiffres"]),
 (12,"La récupération","Pourquoi le repos fait-il partie de l'entraînement ?",
  "L'adaptation se produit entre les séances, pas pendant.",
  ["Les délais de récupération par type d'effort", "Le rôle du sommeil dans la réparation", "Le surentraînement : ce qu'il est vraiment"]),
 (13,"Protéines : combien, quand","Faut-il manger plus de protéines quand on s'entraîne ?",
  "Une fourchette, une répartition, et beaucoup de bruit autour.",
  ["Les apports établis par la littérature", "Ce que la répartition sur la journée change", "Ce que la fenêtre anabolique n'est pas"]),
 (14,"Les suppléments","Quels compléments servent réellement ?",
  "Une poignée ont des preuves, le reste vit de marketing.",
  ["La créatine : le complément le mieux documenté", "Shakers de protéines : de la nourriture en poudre, pratique, pas magique", "BCAA, brûleurs et boosters : ce que disent les essais", "Ce qu'un supplément ne remplace jamais"]),
 (15,"Cardio ou musculation","Faut-il choisir entre cardio et musculation ?",
  "Deux effets différents, souvent opposés à tort.",
  ["Ce que chacun produit", "Ce qu'ils produisent ensemble", "Pourquoi la question est mal posée"]),
 (16,"Les mythes du sport","Quelles idées reçues sur le sport sont fausses ?",
  "Localiser la perte, transformer le gras en muscle, la zone brûle-graisse.",
  ["Ce que dit la physiologie sur chaque idée reçue", "D'où viennent ces croyances"]),
 (17,"Tableau — sports d'endurance","Que produit chaque sport d'endurance ?",
  "Comparaison des activités cardio.",
  ["Dépense, impact, muscles sollicités"]),
 (18,"Tableau — sports de force et mixtes","Que produit chaque sport de force ?",
  "Comparaison des activités de force et mixtes.",
  ["Dépense, impact, muscles sollicités"]),
 (19,"Tableau — activités douces","Que produisent les activités douces ?",
  "Comparaison des activités de faible intensité.",
  ["Dépense, souplesse, accessibilité"]),
 (20,"Une minute vaut mieux que zéro","Un effort minime sert-il à quelque chose ?",
  "L'écart le plus grand se situe entre zéro et un peu, pas entre beaucoup et un peu plus.",
  ["La courbe des bénéfices : la pente est au début", "Ce que produisent quelques minutes quotidiennes", "Pourquoi le tout ou rien fait perdre le tout"]),
 (21,"Une routine qui tient","Comment installer une pratique durable ?",
  "Une pratique qui dure se conçoit sur ses contraintes, pas sur ses ambitions.",
  ["Le rôle de la fréquence contre l'intensité", "Ce qui rend une séance reproductible", "Le plancher plutôt que le plafond"]),
 (22,"Bouger toute la journée","Faut-il bouger plus, ou s'entraîner plus ?",
  "L'activité diffuse pèse davantage que la séance dans la dépense totale.",
  ["Le NEAT appliqué au quotidien", "Ce que la position assise prolongée modifie"]),
 (23,"Récapitulatif — où part l'énergie","Où part l'énergie, et sur quoi peut-on agir ?",
  "Ce qui se pilote, ce qui s'influence, ce qui ne bouge pas.",
  ["Les trois catégories", "Où porter l'effort si on ne peut en porter qu'un"]),
],
5: [
 (1,"Le corps qui résiste","Pourquoi la perte de poids ralentit-elle toujours ?",
  "Le corps s'adapte : il dépense moins et réclame plus.",
  ["La baisse du métabolisme au-delà de la perte de masse", "La baisse du NEAT, involontaire et invisible", "La hausse de la faim"]),
 (2,"Le set-point","Le corps défend-il un poids ?",
  "Une zone défendue plutôt qu'un point, et défendue plus fort vers le bas.",
  ["Ce que le modèle explique", "Ce qu'il n'explique pas", "Pourquoi la défense est asymétrique"]),
 (3,"L'effet yoyo","Pourquoi reprend-on plus qu'on n'avait perdu ?",
  "Les adaptations survivent à la perte et facilitent la reprise.",
  ["Ce qui persiste après le retour au poids initial", "Les données de suivi à long terme", "Ce que chaque cycle laisse"]),
 (4,"La volonté s'épuise","Pourquoi la volonté ne suffit-elle pas ?",
  "Un effort qui demande de lutter en permanence a une date d'expiration.",
  ["Ce que coûte la vigilance permanente", "Le moment de bascule vers l'abandon", "Pourquoi ce n'est pas un défaut de caractère"]),
 (5,"Les interdits se retournent","Pourquoi les aliments interdits deviennent-ils obsédants ?",
  "La restriction cognitive fabrique l'envie qu'elle voulait éteindre.",
  ["Ce que produit une interdiction sur l'attention", "L'effet « foutu pour foutu » après l'écart", "Pourquoi les listes d'interdits échouent"]),
 (6,"Les régimes à la mode","Pourquoi tous les régimes marchent-ils… au début ?",
  "Tous créent un déficit caché ; aucun ne survit à sa propre monotonie.",
  ["Le déficit déguisé derrière chaque méthode", "Ce que les comparaisons directes montrent à un an", "La seule variable qui prédit le résultat : la tenue dans le temps"]),
 (7,"Le cortisol","Que fait vraiment le cortisol ?",
  "Une hormone nécessaire, accusée au-delà de ce qu'elle fait.",
  ["Son rôle normal dans la journée", "Ce qu'un excès chronique produit", "Ce qu'on lui attribue à tort"]),
 (8,"L'inflammation silencieuse","Qu'est-ce que l'inflammation de bas grade ?",
  "Un état discret, mesurable, associé à beaucoup de choses.",
  ["Ce qu'on mesure et comment", "Ce qui l'entretient", "La prudence nécessaire sur les liens de causalité"]),
 (9,"L'intestin parle au cerveau","L'intestin commande-t-il l'humeur et l'appétit ?",
  "Un axe de communication réel, largement surinterprété.",
  ["Les voies de communication établies", "Ce que les études animales ne prouvent pas chez l'humain", "L'état honnête du savoir"]),
 (10,"Vieillir","Qu'est-ce qui change après quarante ans ?",
  "La masse maigre baisse, la dépense suit, les besoins changent.",
  ["La sarcopénie et son rythme", "Ce qui ralentit vraiment, et de combien", "Ce qui reste modifiable"]),
 (11,"Le corps féminin","En quoi le métabolisme féminin diffère-t-il ?",
  "Cycle hormonal, composition corporelle, et des recommandations calquées sur les hommes.",
  ["Ce que le cycle modifie sur la dépense et l'appétit", "Les différences de composition corporelle", "Ce que la recherche a longtemps ignoré"]),
 (12,"Récapitulatif — l'échec annoncé","Qu'est-ce qui condamne un régime avant même de commencer ?",
  "Les mécanismes de la partie, réunis : ce qu'un plan doit éviter pour tenir.",
  ["Les causes d'échec par ordre de fréquence", "Celles qui relèvent du corps, celles du plan lui-même"]),
],
6: [
 (1,"Faire du sport sans maigrir","Pourquoi le sport seul fait-il si peu maigrir ?",
  "La séance brûle moins qu'affiché, et le corps reprend une partie du reste.",
  ["La compensation alimentaire : la faim d'après-séance", "La compensation d'activité : le NEAT qui baisse le jour du sport", "La séance surestimée par les machines et les montres", "Ce que le sport fait quand même, et qui ne se voit pas sur la balance"]),
 (2,"Pourquoi on stagne","Pourquoi les progrès s'arrêtent-ils ?",
  "L'adaptation rend efficace, donc moins coûteux.",
  ["Le principe de surcharge progressive", "Les paliers normaux", "Ce qui distingue une stagnation d'un plateau réel"]),
 (3,"Pourquoi la majorité abandonne","Pourquoi arrête-t-on le sport ?",
  "Les causes d'abandon sont documentées, et elles ne sont pas la motivation.",
  ["Les causes réelles d'arrêt", "Le seuil d'effort qui ne tient pas dans une semaine ordinaire", "Ce que « manquer de motivation » recouvre"]),
 (4,"S'entraîner sans manger assez","Pourquoi s'entraîner ne suffit-il pas pour prendre du muscle ?",
  "Le muscle se construit avec un signal et des matériaux ; l'entraînement ne fournit que le signal.",
  ["Le surplus nécessaire, et sa taille réelle", "Les protéines comme matériau, pas comme potion", "Pourquoi l'entraînement sans les matériaux n'agrandit rien"]),
 (5,"Le hardgainer n'existe pas","Pourquoi certains ne prennent-ils jamais un gramme ?",
  "Les études qui nourrissent des « hardgainers » trouvent toujours la même chose : ils mangent moins qu'ils ne le pensent.",
  ["Les apports déclarés contre les apports mesurés", "Le NEAT élevé et l'appétit court", "Ce qui marche : la densité énergétique lue à l'envers"]),
 (6,"Le rythme réel du muscle","Combien de muscle peut-on prendre, et en combien de temps ?",
  "Les ordres de grandeur mesurés, loin des transformations en douze semaines.",
  ["Les gains de première année, puis la décroissance", "Ce que les transformations spectaculaires ne disent pas", "Pourquoi des attentes fausses fabriquent des abandons"]),
 (7,"Récapitulatif — l'effort et le résultat","Qu'est-ce qui sépare l'effort du résultat ?",
  "Les causes d'échec de l'entraînement, côté perte et côté muscle.",
  ["Les erreurs qui coûtent le plus", "Ce qui relève de l'attente, ce qui relève de la méthode"]),
],
7: [
 (1,"Ce qui promet d'aider","Quelles aides existent, et qui y a droit ?",
  "Médicaments, chirurgie, dopage : le paysage, et ses conditions d'accès.",
  ["Les trois familles, et où chacune commence", "Ce qui se prescrit, ce qui s'encadre, ce qui s'interdit", "Pourquoi ce livre les décrit sans les recommander ni les juger"]),
 (2,"Les médicaments de la faim","Que font les nouveaux médicaments de la perte de poids ?",
  "Les analogues du GLP-1 imitent une hormone de satiété — et n'agissent que tant qu'ils sont là.",
  ["Le mécanisme : une hormone de satiété prolongée", "Les pertes mesurées dans les essais cliniques", "Ce que montrent les données à l'arrêt du traitement"]),
 (3,"Ce que fait une chirurgie de l'obésité","Que change un bypass ou une sleeve ?",
  "Moins un estomac rétréci qu'un signal hormonal transformé.",
  ["Restriction et malabsorption : la mécanique visible", "La chute de la ghréline : l'effet le moins connu et le plus puissant", "Ce que l'opération change à la faim, pas seulement à la contenance"]),
 (4,"Après l'opération","Pourquoi peut-on reprendre du poids après une chirurgie ?",
  "L'opération transforme les signaux ; elle ne suspend pas l'adaptation.",
  ["Les données de reprise à cinq et dix ans", "Les mécanismes du livre qui continuent de s'appliquer", "Ce qui distingue ceux qui maintiennent"]),
 (5,"Le dopage","Que fait le dopage, et à quel prix ?",
  "Du muscle plus vite, un coût physiologique documenté.",
  ["Ce que les stéroïdes changent à la synthèse musculaire", "Ce qui reste et ce qui part à l'arrêt", "Les coûts documentés, du cœur à la fertilité"]),
 (6,"Récapitulatif — alors, est-ce que ça marche ?","Que retenir de ces aides ?",
  "Ce que chacune change, ce qu'elle coûte, et ce qu'aucune ne suspend.",
  ["Le tableau des aides : effet mesuré, coût, durée", "Aucune n'annule les mécanismes des parties précédentes", "Pourquoi la suite du livre s'applique aussi à ceux qui y ont recours"]),
],
8: [
 (1,"Rien à supprimer","Faut-il supprimer des aliments pour perdre du poids ?",
  "L'interdiction crée l'envie et prépare l'abandon.",
  ["Ce que produit une restriction cognitive", "Pourquoi les listes d'interdits échouent", "Ce que remplacer veut dire"]),
 (2,"Ce qui fait perdre","Qu'est-ce qui fait perdre du poids ?",
  "Un déficit énergétique, quelle que soit la manière dont il est obtenu.",
  ["Le principe, et pourquoi il n'est pas contestable", "Les nombreuses façons de l'obtenir", "Ce que ce principe ne dit pas"]),
 (3,"Combien, combien de temps","Quelle taille de déficit, et sur quelle durée ?",
  "Un déficit trop grand se paie ; un déficit petit se tient.",
  ["Les ordres de grandeur", "Ce qu'un déficit trop fort déclenche", "Le rythme de perte que la littérature juge tenable"]),
 (4,"Cinq kilos par an","Vaut-il mieux perdre lentement ?",
  "Une perte lente et définitive dépasse une perte rapide reprise.",
  ["La comparaison sur cinq ans", "Ce que la vitesse coûte en masse maigre", "Le calcul qu'on ne fait jamais"]),
 (5,"Maintenir","Comment garde-t-on un poids une fois atteint ?",
  "La phase la moins étudiée, la plus longue, et celle qui décide de tout.",
  ["Ce que font les personnes qui maintiennent", "Pourquoi maintenir demande autre chose que perdre"]),
 (6,"Du savoir au réflexe","Comment passe-t-on de comprendre à faire ?",
  "Ce qui devient automatique cesse de demander de la volonté.",
  ["Le rôle du contexte contre celui de la décision", "Les changements qui ne demandent pas d'arbitrage quotidien"]),
 (7,"L'assiette équilibrée","À quoi ressemble une assiette équilibrée ?",
  "Un repère visuel qui remplace le comptage.",
  ["Les proportions et leur justification", "Pourquoi un visuel tient mieux qu'un chiffre"]),
 (8,"Une portion, c'est combien","Comment évaluer une portion sans balance ?",
  "Des repères corporels, transportables partout.",
  ["Les repères à la main", "Leur marge d'erreur réelle"]),
 (9,"Adapter son assiette","Comment ajuster son assiette à son objectif ?",
  "Les mêmes proportions, déplacées.",
  ["Ce qui bouge selon l'objectif", "Ce qui ne bouge jamais"]),
 (10,"Le petit-déjeuner","Que vaut un petit-déjeuner, et faut-il en prendre un ?",
  "Ce que la composition change sur la matinée.",
  ["Sucré contre protéiné : l'effet sur la faim de 11 h", "Ce que dit la littérature sur le fait de le sauter"]),
 (11,"Le déjeuner","Comment composer un déjeuner qui tient l'après-midi ?",
  "La composition décide de l'heure du prochain creux.",
  ["Ce qui prolonge la satiété", "Le rôle de l'ordre des aliments"]),
 (12,"Le dîner","Le dîner doit-il être léger ?",
  "Ce que l'heure et la composition changent sur la nuit.",
  ["L'effet sur le sommeil", "Ce que « léger » veut dire concrètement"]),
 (13,"Le creux de dix-sept heures","Pourquoi a-t-on faim en fin d'après-midi ?",
  "Un creux prévisible, dont la cause se trouve au repas précédent.",
  ["Le mécanisme du creux", "Ce qui l'a préparé plusieurs heures avant"]),
 (14,"Grignoter mieux","S'il faut grignoter, comment le faire ?",
  "À énergie égale, tous les en-cas ne se valent pas.",
  ["Le classement par densité et par volume", "Ce qui tient jusqu'au repas"]),
 (15,"Les faux amis du quotidien","Quels aliments réputés sains ne le sont pas ?",
  "Jus, barres de céréales, produits allégés, yaourts aux fruits.",
  ["Les cas les plus courants, chiffres à l'appui", "Ce qui crée l'illusion"]),
 (16,"Allonger les heures sans manger","Le jeûne intermittent apporte-t-il quelque chose ?",
  "Un cadre horaire dont l'effet propre reste discuté à apport égal.",
  ["Les protocoles courants", "Ce que les essais montrent à apport égal", "L'autophagie : ce qui est établi chez l'humain"]),
 (17,"Mieux dormir dès ce soir","Que peut-on changer pour mieux dormir ?",
  "Quelques facteurs ont des preuves solides, beaucoup n'en ont pas.",
  ["Lumière, température, horaires, caféine", "Ce qui a des preuves et ce qui relève du rituel"]),
 (18,"Faire baisser le stress","Que peut-on faire contre le stress, réellement ?",
  "Les interventions testées, avec leur effet mesuré.",
  ["Ce qui a été mesuré en essai", "L'écart entre efficacité et faisabilité"]),
 (19,"La lumière","La lumière change-t-elle quelque chose au métabolisme ?",
  "Elle règle l'horloge interne, qui règle beaucoup de choses.",
  ["Lumière du matin et calage de l'horloge", "Lumière du soir et endormissement"]),
 (20,"Manger anti-inflammatoire","Peut-on réduire l'inflammation par l'assiette ?",
  "Certains schémas alimentaires ont un effet mesuré ; les aliments miracles n'existent pas.",
  ["Ce que montrent les schémas alimentaires étudiés", "Pourquoi aucun aliment isolé ne suffit"]),
 (21,"Manger à plusieurs","Mange-t-on autrement à plusieurs ?",
  "La présence des autres modifie la quantité mangée, de façon mesurée.",
  ["L'effet de facilitation sociale", "Ce que l'isolement change"]),
 (22,"Au restaurant","Comment décider au restaurant ?",
  "Une grille de lecture qui tient sans calcul.",
  ["Les questions à se poser sur une carte", "Ce qui change le plus pour le moins d'effort"]),
 (23,"Le classement des fast-foods","Que vaut vraiment un repas de fast-food ?",
  "Comparaison des chaînes et des menus, à portion réelle.",
  ["Le classement par densité énergétique", "Les écarts à l'intérieur d'une même enseigne"]),
 (24,"Le bar sans les dégâts","Comment limiter la facture d'une soirée ?",
  "L'énergie liquide s'ajoute sans rassasier, et lève les freins.",
  ["Les valeurs par verre", "L'effet sur ce qui est mangé ensuite", "Les arbitrages qui changent le plus"]),
 (25,"Faire ses courses","Comment les courses décident-elles du reste de la semaine ?",
  "Ce qui entre chez soi détermine ce qui sera mangé.",
  ["Le choix se fait au magasin, pas devant le placard", "Ce que l'agencement des rayons exploite"]),
 (26,"Nourrir ses enfants","Comment nourrir un enfant sans lui transmettre le problème ?",
  "Les préférences se forment tôt, et les interdits se retournent.",
  ["Ce que l'exposition répétée produit", "Pourquoi interdire renforce l'attrait", "Le rôle de l'exemple contre celui de la consigne"]),
 (27,"Manger plus sans appétit","Comment manger plus quand l'appétit ne suit pas ?",
  "La densité énergétique se lit aussi à l'envers : moins de volume pour plus d'énergie.",
  ["Les aliments denses qui ne remplissent pas", "Le liquide qui nourrit sans rassasier — l'atout de celui qui veut prendre", "La fréquence plutôt que la taille des repas"]),
 (28,"Le surplus tenable","Comment prendre du poids sans prendre que du gras ?",
  "Un surplus modeste et un entraînement qui donne au corps une raison de construire.",
  ["La taille du surplus au-delà de laquelle on ne gagne que du gras", "Le rôle de l'entraînement dans la destination du surplus", "Le rythme de prise qui limite la casse"]),
 (29,"Ce livre ne dit pas quoi faire","Que faire de tout cela ?",
  "Le livre s'arrête où la décision commence.",
  ["Ce qui a été décrit", "Ce qui appartient au lecteur, et pourquoi"]),
],
}
